name: LIN_DED_NODE_SCM_CREDENTIALS

on:
  push:
    branches:
    - master

jobs:
  BuildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Azure/functions-action@v1
      id: result
      with:
        app-name: hazeng-fa-github-lin-ded-node
        publish-profile: ${{ secrets.LIN_DED_NODE_SCM_CREDENTIALS }}
    - run: echo "The result is ${{ steps.result.outputs.app-url }}"
