name: WIN_DED_NODE_SCM_CREDENTIALS

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: Azure/functions-action@dev
      id: result
      with:
        app-name: hazeng-fa-github-win-ded-node
        publish-profile: ${{ secrets.WIN_DED_NODE_SCM_CREDENTIALS }}
    - run: echo "The result is ${{ steps.result.outputs.app-url }}"
