name: CI

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: Azure/functions-action@dev
      with:
        id: 'result'
        app-name: 'hazeng-fa-github-win-con-node'
        publish-profile: '<publishData><publishProfile profileName="hazeng-fa-github-win-con-node - Web Deploy" publishMethod="MSDeploy" publishUrl="hazeng-fa-github-win-con-node.scm.azurewebsites.net:443" msdeploySite="hazeng-fa-github-win-con-node" userName="$hazeng-fa-github-win-con-node" userPWD="pyoqHRponPhuaeeg0LNwBqEbkzxmADazokFDvHQL3RDXvLhv4u12rR0L00ZJ" destinationAppUrl="http://hazeng-fa-github-win-con-node.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="hazeng-fa-github-win-con-node - FTP" publishMethod="FTP" publishUrl="ftp://waws-prod-bay-121.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="hazeng-fa-github-win-con-node\$hazeng-fa-github-win-con-node" userPWD="pyoqHRponPhuaeeg0LNwBqEbkzxmADazokFDvHQL3RDXvLhv4u12rR0L00ZJ" destinationAppUrl="http://hazeng-fa-github-win-con-node.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
    - run: echo "The result is ${{ steps.result.outputs.functionapp-url }}"
