name: CI

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: Azure/functions-action@dev
      with:
        id: 'result'
        app-name: 'hazeng-fa-github-win-con-node'
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}
    - run: echo "The result is ${{ steps.result.outputs.functionapp-url }}"
